# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TRULogining' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TRULogining
pod 'XPJLogining', :path => '../'
#pod 'TRUNetworking', :path => '../../TRUNetworking'
#pod 'XPJNetworking'

  target 'TRULoginingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TRULoginingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
